//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegradorWebService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vpsrv.visualset.com.br/PostagemVipp.asmx")]
        public string IntegradorWebService_WSVIPP_PostagemVipp {
            get {
                return ((string)(this["IntegradorWebService_WSVIPP_PostagemVipp"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vipp.visualset.com.br")]
        public string Site {
            get {
                return ((string)(this["Site"]));
            }
            set {
                this["Site"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PEFycmF5T2ZGb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvP" +
            "kRlc3RpbmF0YXJpbzwvTm9tZUF0cmlidXRvPjxDb2x1bmE+MzwvQ29sdW5hPjwvRm9ybWF0YWNhb1BsY" +
            "W5pbGhhPjxGb3JtYXRhY2FvUGxhbmlsaGE+PE5vbWVBdHJpYnV0bz5PYnNlcnZhY2FvNDwvTm9tZUF0c" +
            "mlidXRvPjxDb2x1bmE+NDwvQ29sdW5hPjwvRm9ybWF0YWNhb1BsYW5pbGhhPjxGb3JtYXRhY2FvUGxhb" +
            "mlsaGE+PE5vbWVBdHJpYnV0bz5Eb2N1bWVudG9EZXN0aW5hdGFyaW88L05vbWVBdHJpYnV0bz48Q29sd" +
            "W5hPjQ8L0NvbHVuYT48L0Zvcm1hdGFjYW9QbGFuaWxoYT48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQ" +
            "XRyaWJ1dG8+RW1haWw8L05vbWVBdHJpYnV0bz48Q29sdW5hPjU8L0NvbHVuYT48L0Zvcm1hdGFjYW9Qb" +
            "GFuaWxoYT48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb21lQXRyaWJ1dG8+Q0VQPC9Ob21lQXRyaWJ1dG8+P" +
            "ENvbHVuYT42PC9Db2x1bmE+PC9Gb3JtYXRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48T" +
            "m9tZUF0cmlidXRvPkVuZGVyZWNvPC9Ob21lQXRyaWJ1dG8+PENvbHVuYT43PC9Db2x1bmE+PC9Gb3JtY" +
            "XRhY2FvUGxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvPk51bWVybzwvTm9tZ" +
            "UF0cmlidXRvPjxDb2x1bmE+ODwvQ29sdW5hPjwvRm9ybWF0YWNhb1BsYW5pbGhhPjxGb3JtYXRhY2FvU" +
            "GxhbmlsaGE+PE5vbWVBdHJpYnV0bz5Db21wbGVtZW50bzwvTm9tZUF0cmlidXRvPjxDb2x1bmE+OTwvQ" +
            "29sdW5hPjwvRm9ybWF0YWNhb1BsYW5pbGhhPjxGb3JtYXRhY2FvUGxhbmlsaGE+PE5vbWVBdHJpYnV0b" +
            "z5CYWlycm88L05vbWVBdHJpYnV0bz48Q29sdW5hPjEwPC9Db2x1bmE+PC9Gb3JtYXRhY2FvUGxhbmlsa" +
            "GE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvPkNpZGFkZTwvTm9tZUF0cmlidXRvPjxDb" +
            "2x1bmE+MTE8L0NvbHVuYT48L0Zvcm1hdGFjYW9QbGFuaWxoYT48Rm9ybWF0YWNhb1BsYW5pbGhhPjxOb" +
            "21lQXRyaWJ1dG8+VUY8L05vbWVBdHJpYnV0bz48Q29sdW5hPjEyPC9Db2x1bmE+PC9Gb3JtYXRhY2FvU" +
            "GxhbmlsaGE+PEZvcm1hdGFjYW9QbGFuaWxoYT48Tm9tZUF0cmlidXRvPk9ic2VydmFjYW8xPC9Ob21lQ" +
            "XRyaWJ1dG8+PENvbHVuYT4xNDwvQ29sdW5hPjwvRm9ybWF0YWNhb1BsYW5pbGhhPjxGb3JtYXRhY2FvU" +
            "GxhbmlsaGE+PE5vbWVBdHJpYnV0bz5PYnNlcnZhY2FvMjwvTm9tZUF0cmlidXRvPjxDb2x1bmE+MTU8L" +
            "0NvbHVuYT48L0Zvcm1hdGFjYW9QbGFuaWxoYT48L0FycmF5T2ZGb3JtYXRhY2FvUGxhbmlsaGE+")]
        public string Layout {
            get {
                return ((string)(this["Layout"]));
            }
            set {
                this["Layout"] = value;
            }
        }
    }
}
